import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { makeStyles } from "@material-ui/core/styles";
import Switch from "@material-ui/core/Switch";
import Paper from "@material-ui/core/Paper";
import Grow from "@material-ui/core/Grow";
import FormControlLabel from "@material-ui/core/FormControlLabel";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Open Learning!</h1>

        <p className={styles.description}>
          Start your academic adventure with just one click
          <br></br>
          Open School is a crowd sourced educational website. Many teachers have
          created videos and material to cater online class during the pandemic.
          Now they can upload this content within our course and units framework
          to provide high quality education to any student with internet access.
        </p>

        <div className={styles.grid}>
          <Grow in={true}>
            <a href="/courses/algebra" className={styles.card}>
              <h2>Algebra &rarr;</h2>
              <p>A broad area of mathematics with many applications</p>
            </a>
          </Grow>

          <Grow in={true}>
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Biology &rarr;</h2>
              <p>The study of life and its unifying themes</p>
            </a>
          </Grow>

          <Grow in={true}>
            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Physics &rarr;</h2>
              <p>Discover the rules of the universe and explore</p>
            </a>
          </Grow>
        </div>
      </main>
    </div>
  );
}
